### PR TITLE
Update documentation for HTTP requests secret handling

### PR DESCRIPTION
**Pull request by prakhargupta1**
Closes: https://github.com/mui/mui-toolpad/issues/2944

### CODE REVIEW

**Review by Janpot — APPROVED** [review]
I rewrote the whole section to be a bit more comprehensive and to reflect more acurately the new way of dealing with environment variables. I've added some video and updated screenshot.

**Comment by JerryWu1234** [comment]
> @JerryWu1234 As the original author of [the feature](https://github.com/mui/mui-toolpad/pull/2777), would you mind reviewing this as well?

no problem

**Comment by JerryWu1234** [comment]
it looks great.

image
it would be better If I can see this video.
there is wrong in my local

**Comment by prakhargupta1** [comment]
Thanks. The video works in the docs. I'll merge it.

Screenshot 2023-12-01 at 2 09 59 PM

**Pull request merged**
