### PR TITLE
Disallow access to DOM globals in bindings

### PR DESCRIPTION
**Pull request by Janpot**
This makes it impossible to bind to e.g.

```tsx
JSON.stringify(document.getElementById('hello')?.textContent)
```

As a side-effect this also makes it impossible to bind to `localStorage`. This was never intended to be supported. We will provide an alternative for its use-case.

### CODE REVIEW

**Review by apedroferreira — APPROVED** [review]
Looks good, just hopefully users don't find it confusing to be able to use certain globals but not others.

**Comment by Janpot** [comment]
These are not arbitrarily chosen, these are the globals defined by the ecmascript standard. We just don't support the DOM because we're not a browser.
It shouldn't be more confusing than using any other non-browser javascript runtime. Like node.js.

**Comment by apedroferreira** [comment]
> These are not arbitrarily chosen, these are the globals defined by the ecmascript standard. We just don't support the DOM because we're not a browser. It shouldn't be more confusing than using any other non-browser javascript runtime. Like node.js.

Ok, even `URL` and `URLSearchParams` are available in Node, right? I think the reasoning makes sense!

**Comment by Janpot** [comment]
Yes, latest node versions. I think the most important is that whatever the types say is there is supported.

**Pull request merged**
