### PR TITLE
[Toolpad Editor] Fix Markdown text alignment issue

### LINKED ISSUE #2588: Horizontal alignment not working for Markdown Text component
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:

1. Add a text component to the canvas.
2. Make the mode as Markdown
3. Try to align it from the inspector panel. 

### Current behavior 😯

Markdown text doesn't align correctly.

This issues is same as #2071 . 

https://github.com/mui/mui-toolpad/assets/30728574/60dbbf78-81a9-488c-9d53-26bd3320e3fb

### Expected behavior 🤔

Markdown text should align correctly.

### Context 🔦

_No response_

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

System:
    OS: macOS 13.5
  Binaries:
    Node: 18.17.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.6.7 - /usr/local/bin/npm
  Browsers:
    Chrome: 116.0.5845.140
    Edge: 116.0.1938.62
    Safari: 16.6
  npmPackages:
    @emotion/react:  11.11.1 
    @emotion/styled:  11.11.0 
    @mui/base:  5.0.0-beta.13 
    @mui/core-downloads-tracker:  5.14.7 
    @mui/icons-material:  5.14.7 
    @mui/lab:  5.0.0-alpha.142 
    @mui/material:  5.14.7 
    @mui/monorepo: https://github.com/mui/material-ui.git => 5.14.6 
    @mui/private-theming:  5.14.7 
    @mui/styled-engine:  5.14.7 
    @mui/system:  5.14.7 
    @mui/toolpad:  0.1.25 
    @mui/toolpad-components:  0.1.25 
    @mui/toolpad-core:  0.1.25 
    @mui/toolpad-utils:  0.1.25 
    @mui/types:  7.2.4 
    @mui/utils:  5.14.7 
    @mui/x-data-grid:  6.12.0 
    @mui/x-data-grid-pro:  6.12.0 
    @mui/x-date-pickers:  6.12.0 
    @mui/x-date-pickers-pro:  6.12.0 
    @mui/x-license-pro:  6.10.2 
    @types/react:  18.2.21 
    react:  18.2.0 
    react-dom:  18.2.0 
    typescript: 5.2.2 => 5.2.2 

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### PR DESCRIPTION
**Pull request by rohanprasadofficial**
Fixes #2588 

This PR targets to fix the alignment issues when rendering the markdown text component on the canvas. It was also showing the wrong alignment state on the left panel.

The typography was taking full width not allowing the text to align to correct position.

This is a similar issue to this : https://github.com/mui/mui-toolpad/issues/2071 

### Before : 

https://github.com/mui/mui-toolpad/assets/30728574/0e4dfc44-2f4c-4a8b-aee7-47fc3071ae93

### After : 

https://github.com/mui/mui-toolpad/assets/30728574/cc02ea28-d6c8-40ac-9d5b-20bafa7f2b73

- [x] I've read and followed the [contributing guide](https://github.com/mui/mui-toolpad/blob/master/CONTRIBUTING.md#sending-a-pull-request) on how to create great pull requests.
- [x] I've updated the relevant documentation for any new or updated feature
- [x] I've linked relevant GitHub issue with "Closes #<issue id>"
- [x] I've added a visual demonstration under the form of a screenshot or video

### CODE REVIEW

**Comment by bharatkashyap** [comment]
Looks good to me! Thanks for the contribution @rohanprasadofficial

**Review by bharatkashyap — APPROVED** [review]

**Comment by Janpot** [comment]
Looks good. Shall we add the same as https://github.com/mui/mui-toolpad/pull/2587#issuecomment-1704949837 but with three elements in markdown mode?

**Comment by rohanprasadofficial** [comment]
@Janpot , yes i think we should add it here as well, will add the visual test and push in.

**Review by Janpot — APPROVED** [review]

**Comment by Janpot** [comment]
Thank you!

**Pull request merged**
