### PR TITLE
[docs] Improve the docs

### PR DESCRIPTION
**Pull request by oliviertassinari**
Handle https://github.com/mui/mui-toolpad/pull/2341#discussion_r1273323062

https://deploy-preview-2366--mui-toolpad-docs.netlify.app/toolpad/

### CODE REVIEW

**Review by bharatkashyap — APPROVED** [review]

**Comment by oliviertassinari** [comment]
A few more fixes for the homepage

**Comment by Janpot** [comment]
One thing I noticed is that the padding on this badge feels a bit off

Screenshot 2023-07-25 at 14 58 33

To me it feels unbalanced top vs. bottom.

**Comment by oliviertassinari** [comment]
it looks horrible, agree but I can't reproduce this one:

Screenshot 2023-07-26 at 00 18 42

**Comment by prakhargupta1** [comment]
It would be great if we could deploy these changes today, as I want to direct some of the users to the examples page.

**Comment by bharatkashyap** [comment]
> it looks horrible, agree 

Should we remove the button? It came from the need here: https://github.com/mui/mui-toolpad/issues/2335

**Comment by Janpot** [comment]
I don't see it anymore, not sure what has changed

**Pull request merged**
