### PR TITLE
Fix hud overlay index

### PR DESCRIPTION
**Pull request by bytasv**
- Closes https://github.com/mui/mui-toolpad/issues/917

image

### CODE REVIEW

**Comment by Janpot** [comment]
Did you verify whether the select dropdown still correctly displays over the HUD overlay?

**Comment by bytasv** [comment]
> Did you verify whether the select dropdown still correctly displays over the HUD overlay?

Are you talking about this case?
image

**Comment by Janpot** [comment]
yes

**Comment by bytasv** [comment]
Then I guess the answer is in the screenshot - it does work as expected

**Review by Janpot — APPROVED** [review]

**Pull request merged**
