### PR TITLE
Link Material UI components on Toolpad component docs page 

### PR DESCRIPTION
**Pull request by prakhargupta1**
Not linked:
- chart, file picker, form, image, metric, page-column, page-row.

- [x] I've read and followed the [contributing guide](https://github.com/mui/mui-toolpad/blob/master/CONTRIBUTING.md#sending-a-pull-request) on how to create great pull requests.
- [x] I've updated the relevant documentation for any new or updated feature
- [x] I've linked relevant GitHub issue with "Closes #<issue id>"
- [x] I've added a visual demonstration under the form of a screenshot or video

### CODE REVIEW

**Comment by Janpot** [comment]
These pages are auto-generated from the component definitions 
🤔 I should add to this comment that these files can't be hand edited
https://github.com/mui/mui-toolpad/blob/091c17b1b51be293d0993ffe2a053b664885f736/docs/data/toolpad/reference/components/autocomplete.md?plain=1#L1

**Comment by Janpot** [comment]
> But then why was it randomly done for some components and missed the others?

This should be in every component file under https://github.com/mui/mui-toolpad/tree/master/docs/data/toolpad/reference/components

**Comment by prakhargupta1** [comment]
> > But then why was it randomly done for some components and missed the others?
> 
> This should be in every component file under https://github.com/mui/mui-toolpad/tree/master/docs/data/toolpad/reference/components

The linking is still missing in this PR: https://github.com/mui/mui-toolpad/pull/2456 Eg, for autocomplete but it is there for button component.
I am emphasizing this only because most users would want to be taken to the respective Material UI component doc page.

**Comment by Janpot** [comment]
I think the original idea was to link from Toolpad into Toolpad docs instead of into MUI core docs.
Anyway, I'm pushing https://github.com/mui/mui-toolpad/pull/2456 forward to add descriptions to all components.

**Pull request closed without merging**
