### PR TITLE
a new feature that let user add env variable.

### PR DESCRIPTION
**Pull request by JerryWu1234**
#2616 
- [x] I've read and followed the [contributing guide](https://github.com/mui/mui-toolpad/blob/master/CONTRIBUTING.md#sending-a-pull-request) on how to create great pull requests.
- [x] I've updated the relevant documentation for any new or updated feature.
- [x] I've linked relevant GitHub issue with "Closes #<issue id>".
- [x] I've added a visual demonstration in the form of a screenshot or video.

### CODE REVIEW

**Comment by JerryWu1234** [comment]
image

**Comment by JerryWu1234** [comment]
please help checking before I add a test

**Comment by apedroferreira** [comment]
Good start @JerryWu1234 !
I'm still not 100% sure what the best solution is, but here's what I think we could try now:

What if we change ```params: params: Record<string, string>``` in `execBase` to ```params: [string, BindableAttrValue<string>][]```, so that we always pass the binding entries there instead of the binding values?

That way we don't need the changes you made in [packages/toolpad-core/src/jsRuntime.tsx](https://github.com/mui/mui-toolpad/pull/2767/files#diff-8743c8b985952b64bf101678990a804d780065cb492f3bef76e32f475b425be5) and in [packages/toolpad-app/src/toolpadDataSources/rest/server.ts](https://github.com/mui/mui-toolpad/pull/2767/files#diff-4a7aa1ca4a54a2a0238476a8b5c22e015ba156791d90175b2dcfc49036b0c32e) we just need ```
parameters: resolveBindableEntries(jsRuntime, params, queryScope)```

**Comment by apedroferreira** [comment]
> Good start @JerryWu1234 ! I'm still not 100% sure what the best solution or if this will work without any new issues, but here's what I think we could try:
> 
> What if we change the argument `params: params: Record<string, string>` in `execBase` to `params: [string, BindableAttrValue<string>][]`, so that we always pass the binding entries there instead of the binding values?
> 
> That way we don't need the changes you made in [packages/toolpad-core/src/jsRuntime.tsx](https://github.com/mui/mui-toolpad/pull/2767/files#diff-8743c8b985952b64bf101678990a804d780065cb492f3bef76e32f475b425be5), and in [packages/toolpad-app/src/toolpadDataSources/rest/server.ts](https://github.com/mui/mui-toolpad/pull/2767/files#diff-4a7aa1ca4a54a2a0238476a8b5c22e015ba156791d90175b2dcfc49036b0c32e) we just need `parameters: resolveBindableEntries(jsRuntime, params, queryScope)`

If this suggestion does not work for client-side parameters, we can keep client-side parameters the way they are but handle the server-side parameters separately, the way I said above.

**Comment by apedroferreira** [comment]
Ok, if we can get everything to work in https://github.com/mui/mui-toolpad/pull/2777 we don't need to follow this approach here.

**Comment by JerryWu1234** [comment]
I wil close this pr

**Pull request closed without merging**
