### PR TITLE
Improve docs

### PR DESCRIPTION
**Pull request by prakhargupta1**
- Moved **Create custom component** to the same level. Before and After:

Screenshot 2023-07-31 at 1 28 37 PM Screenshot 2023-07-31 at 1 29 11 PM

- Divided HTTP request and custom functions into separate sections. Before:
Screenshot 2023-07-31 at 2 41 11 PM
After:
Screenshot 2023-08-02 at 10 36 03 AM

- [x] I've read and followed the [contributing guide](https://github.com/mui/mui-toolpad/blob/master/CONTRIBUTING.md#sending-a-pull-request) on how to create great pull requests.
- [x] I've updated the relevant documentation for any new or updated feature
- [x] I've linked relevant GitHub issue with "Closes #<issue id>"
- [x] I've added a visual demonstration under the form of a screenshot or video

### CODE REVIEW

**Comment by prakhargupta1** [comment]
There is one issue, I have a valid path http://localhost:3003/toolpad/concepts/queries/
It is parent to HTTP requests and custom functions but is not being shown maybe because of accordion component limitation. Is there any way to fix it?

**Comment by apedroferreira** [comment]
> http://localhost:3003/toolpad/concepts/queries/

From a quick look at different MUI docs it seems like the accordion headings are never supposed to be clickable sections?
So maybe we could just have the more "general" section be the first sub-item, followed by HTTP requests and custom functions at the same level?

**Review by apedroferreira — APPROVED** [review]
Not sure about doing something like `- HTTP Requests` because I don't see it being done anywhere else in any MUI docs... Other than that this seems good to me so I will approve already.

I noticed that in the other docs sometimes the first item is called "Overview":
Screenshot 2023-08-01 at 17 02 18

**Comment by prakhargupta1** [comment]
> I noticed that in the other docs sometimes the first item is called "Overview":

Thanks for sharing this, looks perfect! I'll merge it today.

**Pull request merged**
