### PR TITLE
[website] Fix GA events going to development

### PR DESCRIPTION
**Pull request by bharatkashyap**
- This is to fix Google Analytics issues going to the "development" instance of Google Analytics

See https://github.com/mui/material-ui/blob/master/docs/pages/_document.js#L34 and 
Screenshot 2022-09-06 at 3 07 20 AM

- Please follow the [the contributing guide on how to create great pull requests](https://github.com/mui/mui-toolpad/blob/master/CONTRIBUTING.md#sending-a-pull-request).

### CODE REVIEW

**Comment by bharatkashyap** [comment]
https://app.netlify.com/teams/mui/builds/63166d6c07c39500080bdfc2

Value of 

```ts
process.env.PULL_REQUEST,
  typeof process.env.PULL_REQUEST,
  JSON.stringify(process.env.PULL_REQUEST),
  ```
  in the deploy preview:

Screenshot 2022-09-06 at 10 36 41 AM

**Comment by Janpot** [comment]
Ok, I understand now. During SSR it always uses the environment variables available on the server. netlify passes `PULL_REQUEST=false` during production build. We are not converting `process.env.PULL_REQUEST` to a boolean in `next.config.js` (like the monorepo does). So it gets interpolated as `"false"`, which is a truthy value, thus the Toolpad docs thinks it's always building a PR preview.

Solution, either:
* do `PULL_REQUEST: process.env.PULL_REQUEST === 'true'` like in the monorepo. (This is kind of brittle, it makes the value of `PULL_REQUEST` a string in some places, and a boolean in other. We're also relying on a variable that is defined by the CI provider)
* just pass `process.env.GA_TAG` and pass the correct value in CI

**Comment by bharatkashyap** [comment]
> Ok, I understand now. During SSR it always uses the environment variables available on the server. netlify passes `PULL_REQUEST=false` during production build. We are not converting `process.env.PULL_REQUEST` to a boolean in `next.config.js` (like the monorepo does). So it gets interpolated as `"false"`, which is a truthy value, thus the Toolpad docs thinks it's always building a PR preview.
> 
> Solution, either:
> 
> * do `PULL_REQUEST: process.env.PULL_REQUEST === 'true'` like in the monorepo. (This is kind of brittle, it makes the value of `PULL_REQUEST` a string in some places, and a boolean in other. We're also relying on a variable that is defined by the CI provider)
> * just pass `process.env.GA_ID` and pass the correct value in CI

Let's go ahead and take the first route for now so that we can defer to the existing way of doing things in the immediate term

**Review by Janpot — APPROVED** [review]

**Comment by oliviertassinari** [comment]
https://github.com/mui/material-ui/pull/34259 should prevent this bug from happening again, making the docs infra less coupled to Toolpad.

**Pull request merged**
