### PR TITLE
[website] Add Toolpad core landing page

### PR DESCRIPTION
**Pull request by prakhargupta1**
Preview: https://deploy-preview-3690--mui-toolpad-docs.netlify.app/toolpad/

- [ ] check repercussions of moving Studio to mui.com/toolpad-studio
- [ ] code snippets to be added
- [ ] add authentication component
- [ ] add page content component

### CODE REVIEW

**Comment by prakhargupta1** [comment]
@Janpot In the features section of https://deploy-preview-3690--mui-toolpad-docs.netlify.app/toolpad/:

1. I tried showcasing dashboard layout component like its done here: [https://mui.com/toolpad/core/react-dashboard-layout/](https://mui.com/toolpad/core/react-dashboard-layout/). Instead of coming in the iframe it comes over the entire page.
2. Notifications snackbar throws some error. 

Can you have a look? Thanks

**Comment by Janpot** [comment]
1. There doesn't seem to be an iframe, so we'll have to wrap the component with something like https://github.com/mui/material-ui/blob/d03b6af3a2789af3c55db59f2991205a1f854103/docs/src/modules/components/DemoSandbox.js#L95. I won't have time to look into this before my holidays.
2. If you're not using the Toolpad app provider, you'll have to wrap your page with a `<NotificationsProvider>` as per [docs](https://mui.com/toolpad/core/react-use-notifications/).

**Comment by prakhargupta1** [comment]
> 1. There doesn't seem to be an iframe, so we'll have to wrap the component with something like https://github.com/mui/material-ui/blob/d03b6af3a2789af3c55db59f2991205a1f854103/docs/src/modules/components/DemoSandbox.js#L95. I won't have time to look into this before my holidays.
Thanks for the direction, I tried adding it, but couldn't make it work.

**Comment by apedroferreira** [comment]
> 1. I tried showcasing dashboard layout component like its done here: https://mui.com/toolpad/core/react-dashboard-layout/. Instead of coming in the iframe it comes over the entire page.
> 2. Notifications snackbar throws some error.
> 
> Can you have a look please?

Taking a look at these 2.

**Review by Janpot — APPROVED** [review]
Fine to merge this and fill in the blank demos later (page container, authentication)

**Pull request merged**
