### PR TITLE
[docs] Use product demo video of the onboarding on the landing page

### PR DESCRIPTION
**Pull request by Janpot**
Something we could consider

Preview: https://deploy-preview-3555--mui-toolpad-docs.netlify.app/toolpad/#hero-container-right-area

### CODE REVIEW

**Comment by prakhargupta1** [comment]
Certainly! Looks great!

**Comment by apedroferreira** [comment]
That's cool, make the product look a lot more "human" somehow :D

**Comment by Janpot** [comment]
closes https://github.com/mui/mui-toolpad/issues/3557

> Edit: personally I don't like that there's no timeline unless in full screen mode - you don't know how long the video will last right away, plus can't skip forward if you want to - not sure if that can be fixed, but probably it can.

Agreed, I added the video controls. not sure why we tried to roll something custom here.

**Review by prakhargupta1 — APPROVED** [review]

**Review by prakhargupta1 — APPROVED** [review]

**Comment by prakhargupta1** [comment]
@apedroferreira I have merged this and we are good for a release! Thanks.

**Comment by oliviertassinari** [comment]
Comparing the experience on:

- https://deploy-preview-3554--mui-toolpad-docs.netlify.app/toolpad/#hero-container-right-area
- https://deploy-preview-3555--mui-toolpad-docs.netlify.app/toolpad/#hero-container-right-area

Overall it felt that 3554 (before) has the worst tradeoff. There are two clear ways to make the previous experience better, either go into a longer-form video with a natural user walk-through, what 3555 achieves, and what Retool used to have. Or we go in the opposite direction, take 3554, flatten the content into shorter videos, and list them as features of Toolpad Studio. What Budibase, Appsmith, and Retool feels closer to now.

So 3555 looks like a clear step forward, it brings context, nice 👍

**Pull request merged**
