### PR TITLE
add icon

### PR DESCRIPTION
**Pull request by JerryWu1234**
#2384 

image
image

I reference this [code](https://docs.astro.build/en/guides/server-side-rendering/#configuring-individual-routes) that I was contributed before.
I copied the way they [code](https://github.com/withastro/astro/blob/f21599671a90c3327307eb6d2f4d5c02e9137207/packages/astro/src/vite-plugin-scanner/scan.ts#L68) 
 
- [x] I've read and followed the [contributing guide](https://github.com/mui/mui-toolpad/blob/master/CONTRIBUTING.md#sending-a-pull-request) on how to create great pull requests.
- [x] I've updated the relevant documentation for any new or updated feature
- [x] I've linked relevant GitHub issue with "Closes #<issue id>"
- [x] I've added a visual demonstration under the form of a screenshot or video

### CODE REVIEW

**Comment by Janpot** [comment]
@JerryWu1234 I don't feel at the moment there is a good solution that doesn't introduce too much tech debt compared to the benefits. I'm inclined to say this issue is not yet up for implementation

**Comment by JerryWu1234** [comment]
> 

Where we can save the `Iconname` on the back-end side is the problem, I think.

Tell me if you have any good idea, however I also will keep going

**Comment by JerryWu1234** [comment]
> @JerryWu1234 I don't feel at the moment there is a good solution that doesn't introduce too much tech debt compared to the benefits. I'm inclined to say this issue is not yet up for implementation

I think it would be better for me if you could share more details about your requirements

**Review by brhndursun — APPROVED** [review]

**Comment by JerryWu1234** [comment]
@Janpot closing or upgrading ?

**Pull request closed without merging**
