### PR TITLE
Allow minimum and maximum value for component number props

### PR DESCRIPTION
**Pull request by apedroferreira**
Initially just intended for this PR to be prep for fixing this issue https://github.com/mui/mui-toolpad/issues/826, by using a single source of truth for the minimum component dimensions. But it seems like it's actually a solution, so it closes https://github.com/mui/mui-toolpad/issues/826.
Also closes https://github.com/mui/mui-toolpad/issues/461

Using it already for `Select` component minimum width as an example.

https://user-images.githubusercontent.com/10789765/187513853-ed12ff95-b256-4cf0-90e4-aa616ca933ec.mov

### CODE REVIEW

**Comment by Janpot** [comment]
proptype is based on json-schema, I think  that can describe min and max values. perhaps we should just reuse that?

**Comment by Janpot** [comment]
I'm still not understanding the minimum width use case and how it should behave. Suppose minimum width is 50px, and I put 100 Selects in one row, what happens? what overflows or wraps?

**Comment by apedroferreira** [comment]
> proptype is based on json-schema, I think that can describe min and max values. perhaps we should just reuse that?

didn't know about that, i'll take a look

**Comment by apedroferreira** [comment]
Looks like I already solved the whole issue in this PR after all, slightly unintentionally:

https://user-images.githubusercontent.com/10789765/187966124-55b8dea7-7fbc-4192-addb-ad59e64dcc36.mov

I've tested a bit and basically as long as we don't set a minimum width in the component CSS this kind of issue does not happen, the components always adjust to the width of the container.
 If we make the screen very very narrow and have a lot of components they do overflow as it's inevitable, but I think the best option is to just let that happen rather than hiding the overflow.

Screen Shot 2022-09-01 at 17 10 39

In the future we can probably improve support for small device screens.

So what do you think? In my opinion we can merge this.
  If you don’t agree with adding the new `width` prop it’s also not strictly necessary, we can remove it and use whatever default values the MUI component uses. 
In my opinion this `width` prop is useful without being detrimental - it gives the user more control over how the element looks, and it sets a minimum width that doesn’t look so bad when the select is empty, just like the minimum width before this PR.
But the `width` prop is just an extra thing.

**Comment by apedroferreira** [comment]
Also if you like this idea we can disable the width control when full-width is enabled, I just don't want to do it ahead of time if we don't want to go in this direction.

**Review by Janpot — APPROVED** [review]
👌

**Comment by prakhargupta1** [comment]
👌

**Pull request merged**
