### PR TITLE
v0.5.0

### PR DESCRIPTION
**Pull request by apedroferreira**
v0.5.0 release

### CODE REVIEW

**Comment by apedroferreira** [comment]
Atypical release since we're releasing the CLI but the version of `@toolpad/core` isn't out yet, gonna ignore the failing checks because of that.

**Comment by Janpot** [comment]
I tweaked a bit the text. @prakhargupta1 can you take a look?

**Review by Janpot — APPROVED** [review]

**Comment by prakhargupta1** [comment]
> I tweaked a bit the text. @prakhargupta1 can you take a look?

The edits look good to me!

**Comment by Janpot** [comment]
> I think we can ignore the failing checks because of that.

Will fix separately

**Pull request merged**
