### PR TITLE
Add new custom GA events to demo

### PR DESCRIPTION
**Pull request by apedroferreira**
New custom Google Analytics events for the Toolpad demo.
Closes https://github.com/mui/mui-toolpad/issues/1535

The `toolpad_app_created` event already includes `app_template_id`, so it wasn't necessary to add anything new to know which template was used.

**New events:** 

- `toolpad_app_continue_latest`
Measures when user went to continue working on latest app. Includes `app_id`.

- `toolpad_self_host_click`
Measures click on self-host link. Includes `app_id` and an additional parameter `source` that tells whether the user clicked the self-host link in the demo bar or the query panel (see screenshots).

Screenshot 2023-01-19 at 19 40 29
Screenshot 2023-01-19 at 19 49 35

- `toolpad_roadmap_click`
Measures click on roadmap link in demo bar. Includes `app_id`.

- `toolpad_schedule_demo_click`
Measures click on "schedule demo" link in demo bar. Includes `app_id`.

### CODE REVIEW

**Comment by Janpot** [comment]
Some of these wouldn't be more interesting to solve with UTM parameters on the links?

**Comment by apedroferreira** [comment]
> Would it be more interesting to solve these with UTM parameters on the links? I feel like it could be more powerful.

I don't know exactly how UTM parameters work, but if they send an event automatically by clicking a link it should be a good idea. I had the idea that they only worked if the target page has Google Analytics (in which case this would still work for the self-host button anyway).
I'll try that out and look more into UTM params.

**Comment by apedroferreira** [comment]
I've added UTM parameters to the links according to what I've read about how they should work, but I'm not sure how this replaces the usefulness of having custom events directly in Toolpad?

From what I've read, outbound clicks are tracked automatically with the `click` event, however in the GA dashboard it does not seem easy to view all `click` events distributed by which destination link they used.

And I guess that UTM params in links that lead to the MUI docs could be used to track where traffic came from - but having custom events in Toolpad's Analytics could be an easier way to view and analyze this data, and easier to integrate with funnel metrics and that kind of stuff if we wanted to?

**Comment by apedroferreira** [comment]
I've removed UTM params from the links to roadmap and scheduling demo. 
Kept UTM params in the links to the Toolpad docs, just in case.
Will merge this tomorrow or a bit later if there's no more feedback!

**Pull request merged**
