### PR TITLE
Make queries capable of mutations

### PR DESCRIPTION
**Pull request by Janpot**
Step 1 of https://github.com/mui/mui-toolpad/issues/990

https://user-images.githubusercontent.com/2109932/194826423-aa7c8a62-731d-4fbe-a813-f85e88d9b28b.mov

To Do list:
- [ ] Migrate existing mutations to queries (blocked on https://github.com/mui/mui-toolpad/pull/776)
- [ ] Remove current "migrations" feature in favor of queries
- [ ] https://github.com/mui/mui-toolpad/issues/1121
- [ ] Automatically switch to mutation mode when user selects non-idempotent HTTP method in the fetch datasource

### CODE REVIEW

**Comment by apedroferreira** [comment]
Just an idea, not sure if it's good, but what if "Fetch on page load" was just a checkbox too?

**Review by apedroferreira — APPROVED** [review]

**Comment by Janpot** [comment]
Currently it kind of cycles between two modes. idempotent and non-idempotent queries. I feel like a checkbox doesn't clearly convey that it's two fundamentally different things. A checkbox to me tells me turning something on or off, and here so much more is happening. Somehow we need to make clear that in one mode it's just "fetch when you ask" and the other mode is "Toolpad can fetch however much they want, as long as they do whateevr they can to get the data on the page". "fetch on page load" still sort of communicates to me that there will be only one fetch happening, which is not true.

**Comment by apedroferreira** [comment]
> Currently it kind of cycles between two modes. idempotent and non-idempotent queries. I feel like a checkbox doesn't clearly convey that it's two fundamentally different things. A checkbox to me tells me turning something on or off, and here so much more is happening. Somehow we need to make clear that in one mode it's just "fetch when you ask" and the other mode is "Toolpad can fetch however much they want, as long as they do whateevr they can to get the data on the page". "fetch on page load" still sort of communicates to me that there will be only one fetch happening, which is not true.

Got it, makes sense. Maybe the text in the selector options can make that behavior more obvious somehow? Maybe something like "update automatically" or "refetch on change", not sure...
But yeah also in case we end up having different modes I think a selector for the mode actually seems good.

**Comment by Janpot** [comment]
@apedroferreira I changed it to "Fetch at any time to always be available on the page", what do you think?

**Pull request merged**
