### PR TITLE
[core] `NodeReference` type for references to nodes

### PR DESCRIPTION
**Pull request by bharatkashyap**
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/material-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

- Add a new `NodeReference` type to track references to nodes
- In preparation for #658

### CODE REVIEW

**Comment by Janpot** [comment]
Looking good. Would it make sense to abstract all `.$$ref` access behind
```tsx
// ./appDom.js
export function ref(nodeId: NodeId): NodeReference;
export function deref(ref: NodeReference): NodeId;
```

**Comment by bharatkashyap** [comment]
> Looking good. Would it make sense to abstract all `.$$ref` access behind
> 
> ```tsx
> // ./appDom.js
> export function ref(nodeId: NodeId): NodeReference;
> export function deref(ref: NodeReference): NodeId;
> ```

Would this look something like:
```ts
//ToolpadApp.tsx

- navigateToPage(page.$$ref);
+ navigateToPage(appDom.deref(page));

```

**Comment by Janpot** [comment]
> Would this look something like

Exactly, hiding away the implementation details

**Review by Janpot — APPROVED** [review]
👍 nice

**Pull request merged**
