### PR TITLE
[core] Use `readonly` for Editable Text

### PR DESCRIPTION
**Pull request by bharatkashyap**
- Partial fix of https://github.com/mui/mui-toolpad/issues/2360 (P2)

https://github.com/mui/mui-toolpad/assets/19550456/cc688589-cd0c-4a59-928f-4bdb5495e682

### CODE REVIEW

**Comment by Janpot** [comment]
What's the difference between a `<EditableText readonly />` and a `<Typography />`?

**Comment by apedroferreira** [comment]
> What's the difference between a `<EditableText readonly />` and a `<Typography />`?
> 
> I feel like there is some code to be shared with #2728 around creating/editing tree items. I'm not sure whether EditableText is the right basis for editable tree items 🤔

I completely replaced EditableText with the new tree item component in my PR, it felt like the best approach :/ But let me know if there are any advantages here that I'm missing and we can switch back.

**Comment by Janpot** [comment]
> I completely replaced EditableText with the new tree item component in the hierarchy explorer in my PR, it felt like the best approach :/ But let me know if there are any advantages here that I'm missing and we can switch back.

No, I agree, it's tempting to try and reuse editable text for editable tree items, but I don't believe it's a good fit.

**Comment by bharatkashyap** [comment]
> I completely replaced EditableText with the new tree item component in the hierarchy explorer in my PR, it felt like the best approach :/ But let me know if there are any advantages here that I'm missing and we can switch back.
> 
> Edit: also maybe it's useful to create a hook to share some similar logic between those 2 components, I didn't really look into that.

Ah, I hadn't noticed that. To me it looks fine to continue with the approach in #2728 for Tree Items.  I feel we can preserve this fix for `EditableText` regardless.

> What's the difference between a `<EditableText readonly />` and a `<Typography />`?
I was previously switching between a `<TextField>` and a `<Typography>` for the `<EditableText>` but found it to be better form to only switch attributes on the same component instead of replacing entire markup blocks - the latter causes subtle layout shifts  and styling inconsistencies which require duplication to be fixed, among other things.

**Comment by bharatkashyap** [comment]
Closing since we aren't using this anymore

**Pull request closed without merging**
